version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: zoo_container
    restart: always
    environment:
      POSTGRES_USER: zoo_admin
      POSTGRES_PASSWORD: zoo_password
      POSTGRES_DB: zoo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
    driver: local
